package springrest.model;
// Generated Jun 14, 2017 4:42:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name="cities"
    ,catalog="java_assignment"
)
public class Cities  implements java.io.Serializable {


     private Integer cityId;
     private String cityName;
     private Set<Hotels> hotelses = new HashSet<Hotels>(0);

    public Cities() {
    }

    public Cities(String cityName, Set<Hotels> hotelses) {
       this.cityName = cityName;
       this.hotelses = hotelses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="city_id", unique=true, nullable=false)
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    
    @Column(name="city_name", length=45)
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cities")
    public Set<Hotels> getHotelses() {
        return this.hotelses;
    }
    
    public void setHotelses(Set<Hotels> hotelses) {
        this.hotelses = hotelses;
    }




}


