package springrest.model;
// Generated Jun 14, 2017 12:02:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cities generated by hbm2java
 */
public class Cities  implements java.io.Serializable {


     private Integer cityId;
     private String cityName;
     private Set hotelses = new HashSet(0);

    public Cities() {
    }

    public Cities(String cityName, Set hotelses) {
       this.cityName = cityName;
       this.hotelses = hotelses;
    }
   
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Set getHotelses() {
        return this.hotelses;
    }
    
    public void setHotelses(Set hotelses) {
        this.hotelses = hotelses;
    }




}


