package springrest.model;
// Generated Jun 14, 2017 12:02:57 PM by Hibernate Tools 4.3.1



/**
 * Hotels generated by hbm2java
 */
public class Hotels  implements java.io.Serializable {


     private Integer id;
     private Cities cities;
     private String hotelName;
     private String hotelAddress;

    public Hotels() {
    }

	
    public Hotels(Cities cities) {
        this.cities = cities;
    }
    public Hotels(Cities cities, String hotelName, String hotelAddress) {
       this.cities = cities;
       this.hotelName = hotelName;
       this.hotelAddress = hotelAddress;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cities getCities() {
        return this.cities;
    }
    
    public void setCities(Cities cities) {
        this.cities = cities;
    }
    public String getHotelName() {
        return this.hotelName;
    }
    
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }
    public String getHotelAddress() {
        return this.hotelAddress;
    }
    
    public void setHotelAddress(String hotelAddress) {
        this.hotelAddress = hotelAddress;
    }




}


