package springrest.model;
// Generated Jun 14, 2017 4:42:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hotels generated by hbm2java
 */
@Entity
@Table(name="hotels"
    ,catalog="java_assignment"
)
public class Hotels  implements java.io.Serializable {


     private Integer id;
     private Cities cities;
     private String hotelName;
     private String hotelAddress;

    public Hotels() {
    }

	
    public Hotels(Cities cities) {
        this.cities = cities;
    }
    public Hotels(Cities cities, String hotelName, String hotelAddress) {
       this.cities = cities;
       this.hotelName = hotelName;
       this.hotelAddress = hotelAddress;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_id", nullable=false)
    public Cities getCities() {
        return this.cities;
    }
    
    public void setCities(Cities cities) {
        this.cities = cities;
    }

    
    @Column(name="hotel_name", length=45)
    public String getHotelName() {
        return this.hotelName;
    }
    
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }

    
    @Column(name="hotel_address", length=45)
    public String getHotelAddress() {
        return this.hotelAddress;
    }
    
    public void setHotelAddress(String hotelAddress) {
        this.hotelAddress = hotelAddress;
    }




}


